"""
アプリケーション設定
"""

# ウィンドウ設定
WINDOW_TITLE = "ITパスポート試験学習ツール"
WINDOW_MIN_WIDTH = 1000
WINDOW_MIN_HEIGHT = 700
WINDOW_DEFAULT_WIDTH = 1200
WINDOW_DEFAULT_HEIGHT = 800

# 出題設定
DEFAULT_QUESTION_COUNT = 10
MAX_QUESTION_COUNT = 100
MIN_QUESTION_COUNT = 1

# データベース設定
DATABASE_FILENAME = "app.db"
DATABASE_DIRECTORY = "data"

# ログ設定
LOG_LEVEL = "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
LOG_FILE = "logs/app.log"

# 試験設定
TOTAL_QUESTIONS_IN_TEST = 100  # ITパスポート試験の標準問題数
TEST_TIME_MINUTES = 120  # 試験時間（分）

# UI設定
ENABLE_DARK_MODE = True
SHOW_TIPS_ON_STARTUP = True
